# Generated by Django 4.2 on 2023-05-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiguresAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employed_alumin', models.CharField(max_length=10)),
                ('graduates', models.CharField(max_length=10)),
                ('commitment_percentage', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100)),
                ('terms_conditions', models.BooleanField(default=True)),
            ],
        ),
    ]
