# Generated by Django 4.2 on 2023-05-04 17:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('description', models.TextField(default=None)),
                ('profile_link', models.URLField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=150)),
                ('image', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='images')),
                ('logo', models.CharField(max_length=150)),
            ],
        ),
    ]
